apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol 
  labels:
    storage-type: nfs
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /shared 
    server: 192.168.26.10
  persistentVolumeReclaimPolicy: Retain 