apiVersion: v1
kind: Pod
metadata:
  name: hello-nfs-pod 
  labels:
    name: hello-nfs-pod
spec:
  containers:
    - name: hello-nfs-pod
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol 
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc 