apiVersion: v1
kind: Pod
metadata:
  name: java-resource-tester-pod
spec:
  containers:
  - name: java-resource-tester
    image: sunnyvale/resource-tester:1.0
    imagePullPolicy: Always
    resources:
      requests:
        memory: "60Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    #env:
    #  - name: JAVA_OPTS
    #    value: "-Xms128m"