apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: elk
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html